<a href="https://colab.research.google.com/github/Sanju7287/Python-Course-Work/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np)
arr1=np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')
arr2=np.array([[1,2,3],[4,5,6]])
print("2-dim",arr2,sep='\n',end='\n\n')
arr3=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print("multi-dim",arr3,sep='\n')

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>
1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

multi-dim
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
zeros=np.zeros((4,9))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
ones=np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
identity=np.eye(8)
print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
full_array=np.full((6,5),9)
print(full_array)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


range_arr=np.arange(10,-1,-1)
print(range_arr)

In [ ]:
lin_space=np.linspace(0,50,6)
print(lin_space)

[ 0. 10. 20. 30. 40. 50.]


In [ ]:
rand_int=np.random.randint(1,7,(10,10))
print(rand_int)

[[3 3 1 6 4 3 4 6 3 3]
 [1 6 2 4 6 2 2 4 1 3]
 [1 6 2 3 3 1 3 5 1 4]
 [5 2 4 1 1 4 1 3 1 1]
 [1 4 3 6 6 3 5 4 3 2]
 [5 5 2 2 2 5 5 5 2 1]
 [4 5 4 1 4 1 2 4 3 5]
 [2 5 2 6 6 5 6 2 2 2]
 [5 3 4 4 5 2 1 3 6 1]
 [3 3 6 4 1 5 3 6 4 5]]


In [ ]:
rand_float=np.random.rand(3,7)
print(rand_float)

[[0.07406379 0.3627676  0.93925905 0.17070761 0.42332895 0.99427589
  0.69564988]
 [0.69842093 0.23498455 0.9980278  0.72737822 0.94838568 0.68531354
  0.56673102]
 [0.74197112 0.0373953  0.55577373 0.99523119 0.04414267 0.88371792
  0.08975746]]


In [ ]:
rand_norm=np.random.randn(5,5)
print(rand_norm)

[[ 2.28502651 -0.14343616 -0.41814519  0.94759369 -0.86480244]
 [-0.2674804  -1.09472212  0.13257234 -0.9897562  -1.47327748]
 [-1.57197506 -1.55130476  1.05018055  1.19591122  0.51812094]
 [ 0.16965345  1.66284874  0.36609131  0.80286838  0.03676995]
 [-1.46943602  1.0484798   1.72125841  0.73530572 -0.5143453 ]]


In [ ]:
rand_choice=np.random.choice(['html','css','javascript','python','mysql'],3)
print(rand_choice)

['python' 'mysql' 'html']


In [ ]:
np.random.seed(10)
rand_arr=np.random.randint(6)
print(rand_arr)

1


In [ ]:
arr=np.array([[1,2],[4,5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)

(6, 2)


In [ ]:
reshaped=arr.reshape(4,3)
print(reshaped)

[[1 2 4]
 [5 6 7]
 [8 7 1]
 [2 4 5]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
flattened=a.flatten()
print(flattened)

[1 2 3 4 5 6 7 8]


In [ ]:
transposed=arr.T
print(transposed)

[[1 4 6 8 1 4]
 [2 5 7 7 2 5]]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
30
50
[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0,1])
print(matrix[0:2,1])
print(matrix[1:,:2])
print(matrix[::2,::2])
print(matrix[0:2,1:3])

2
[2 5]
[[4 5]
 [7 8]]
[[1 3]
 [7 9]]
[[2 3]
 [5 6]]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr+1)
print(arr*3)
print(arr**2)
print(arr/3)
print(np.sqrt(arr))

[11 21 31 41 51]
[ 30  60  90 120 150]
[ 100  400  900 1600 2500]
[ 3.33333333  6.66666667 10.         13.33333333 16.66666667]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [1]:
import numpy as np
arr=np.array([1,6,18,29,98])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

152
30.4
18.0


In [2]:
a=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))

3.0
2.0
1.4142135623730951


In [3]:
print(np.min(a))
print(np.max(a))

1
5


In [4]:
a=np.array([1,2,3,4,5])
print(np.cumsum(a))
print(np.cumprod(a))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [7]:
a=np.array([10,20,30,40,50])
print(a%20==0)
print(a[a%20==0])

[False  True False  True False]
[20 40]


In [8]:
a=np.array([3,1,4,2,7,5,7,4])
sorted_a=np.sort(a)
print(sorted_a)

[1 2 3 4 4 5 7 7]


In [9]:
unique_vals=np.unique(a)
print(unique_vals)

[1 2 3 4 5 7]


In [10]:
a=np.array([10,20,30])
view_a=a.view()
view_a[0]=100
print(a,view_a)
copy_a=a.copy()
copy_a[0]=200
print(a,copy_a)

[100  20  30] [100  20  30]
[100  20  30] [200  20  30]


In [11]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[8,9]])
print(np.dot(A,B))

[[21 24]
 [47 54]]


In [12]:
print(np.linalg.det(A))

-2.0000000000000004


In [13]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
eigenvalues,eigenvectors=np.linalg.eig(A)
print(eigenvalues)

[-0.37228132  5.37228132]


In [15]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [16]:
C=np.array([5,11])
solution=np.linalg.solve(A,C)
print(solution)

[1. 2.]


In [17]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
vertical_stack=np.vstack((A,B))
horizontal_stack=np.hstack((A,B))
print(vertical_stack)
print(horizontal_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
split_arr=np.split(np.array([1,2,3,4,5,6]),3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]
